### ISSUE TITLE
Ex - 4 Circuit Decomposition. How to approximate a circuit?

### ISSUE THREAD

**Issue by abhik-99** [qiskit-community/may4_challenge_exercises#11]
Hey, I am a beginner and had recently started reading the Qiskit Textbook when I came across the IBM Quantum Computing Challenge. I have solved exercises 1 through 3 successfully. But exercise 4 has me stumped.

I have tried to implement Hadamard and Rz gates using the generalized U3 Gate. I'm really stuck on the problem and even with all that I have tried I can only boost the norm difference to five 9s after the decimal. Any hints would be much appreciated.

Is there any resources where I can understand how to closely mimic a given circuit's unitary? U was supplied to us after all...

**Comment by amacaluso** [comment]
I haven't solved yet, but there are hints  on Reddit and Slack

**Comment by rajesh-s** [comment]
@amacaluso do you have the working slack invite? The one in README.md doesn't seem to work.

**Comment by amacaluso** [comment]
try this one:

https://join.slack.com/t/qiskit/shared_invite/zt-e4sscbg2-p8NHTezPVkC3r8nV6BIUVw
