### ISSUE TITLE
Stuck at challenge 1 ...... Weird error has kept me angry for 5 hours 😠

### ISSUE THREAD

**Issue by meafs** [qiskit-community/may4_challenge_exercises#12]
See the SS below:
![Screenshot_2020-05-08 IBM Quantum Experience - Qiskit Notebooks](https://user-images.githubusercontent.com/25178594/81374146-66544080-9120-11ea-9871-f693f7d85b2a.png)

**Comment by meafs** [comment]
Still same situation.......

**Comment by rajesh-s** [comment]
You're supposed to run the previous cells before the current cell sequentially. There are dependencies that are imported in the initial cells. Have you tried running each cell sequentially?

**Comment by meafs** [comment]
Yeah. I did.Even added the dependencies in the cell.
I doesn’t work at all. When I ran the same code in VScode it worked as expected. My answer was correct but I couldn’t get going :( 

I have anaconda on my pc, so I am quite familiar with Jupyter Notebook.

**Comment by aasfaw** [comment]
Hi @meafs - you closed the issue. Did you find a good solution?

**Comment by meafs** [comment]
> Hi @meafs - you closed the issue. Did you find a good solution?

Nope.I just gave up.
